"""Add column was_get

Revision ID: 9bb36652270e
Revises: 2224c9e6d6f7
Create Date: 2025-01-04 20:02:35.181486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb36652270e'
down_revision: Union[str, None] = '2224c9e6d6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsinginformations', sa.Column('was_get', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsinginformations', 'was_get')
    # ### end Alembic commands ###
