"""Create parsing information table and init all db

Revision ID: 2224c9e6d6f7
Revises: 
Create Date: 2025-01-04 15:56:01.212204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2224c9e6d6f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsinginformations',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('office', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsinginformations')
    # ### end Alembic commands ###
